server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ewm-service
          uri: lb://ewm-service
          predicates:
            - Path=/events/**, /categories/**, /compilations/**, /users/**, /admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/