-- Таблица для хранения действий пользователей
CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    max_weight DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT uq_user_event UNIQUE (user_id, event_id)
);

-- Индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_user_actions_user_id ON user_actions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_actions_event_id ON user_actions(event_id);
CREATE INDEX IF NOT EXISTS idx_user_actions_timestamp ON user_actions(timestamp);

-- Таблица для хранения сходства мероприятий
CREATE TABLE IF NOT EXISTS event_similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT uq_event_pair UNIQUE (event_a, event_b)
);

-- Индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_event_similarities_event_a ON event_similarities(event_a);
CREATE INDEX IF NOT EXISTS idx_event_similarities_event_b ON event_similarities(event_b);
CREATE INDEX IF NOT EXISTS idx_event_similarities_score ON event_similarities(score);